version: 2
jobs:
  deploy:
    docker:
      - image: cimg/ruby:3.1.2
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            gem update --system
            gem install bundler
      - restore_cache:
          keys:
            - v1-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - v1-gem-cache-{{ arch }}-{{ .Branch }}-
            - v1-gem-cache-{{ arch }}-
      - run: bundle install --path=vendor/bundle && bundle clean
      - save_cache:
          paths:
            - vendor/bundle
          key: v1-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
      - run: JEKYLL_ENV=production bundle exec jekyll build
      - run:
          name: Test
          command: bundle exec htmlproofer ./_site --check-html --disable-external --empty-alt-ignore
      - deploy:
          name: Deploy Release to GitHub
          command: |
            git config user.name "Sivarama Subramanian"
            git config user.email "sivaraam1024@gmail.com"

            git checkout gh-pages
            git pull origin gh-pages

            find . -maxdepth 1 ! -name '_site' ! -name '.git' ! -name '.gitignore' ! -name '.circleci' -exec rm -rf {} \;
            mv _site/* .
            rm -R _site/

            git add -fA
            git commit --allow-empty -m "$(git log source -1 --pretty=%B)"
            git push -f origin gh-pages

            echo "deployed successfully"
workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only: 
                - source
                - circleci-project-setup